services:
  app:
    container_name: btc-viz-app
    image: btc-viz-app
    build: app
    ports:
      - "5234:80"

  proxy:
    container_name: btc-viz-proxy
    image: btc-viz-proxy
    build: proxy
    ports:
      - "7000:80"
